+ python3 duplicate_finder.py --path /share/lasallelab/Logan/
md5sum: /share/lasallelab/Logan/CpG_Me_NovaPilot/LO_11_S9_L002/LO_11_S9_L002_1_val_1_bismark_bt2_pe.deduplicated_splitting_report.txt: No such file or directory
Traceback (most recent call last):
  File "duplicate_finder.py", line 63, in <module>
    checksum_byte = subprocess.check_output(['md5sum', f'{key}'])
  File "/software/anaconda3/4.8.3/lssc0-linux/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/software/anaconda3/4.8.3/lssc0-linux/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['md5sum', '/share/lasallelab/Logan/CpG_Me_NovaPilot/LO_11_S9_L002/LO_11_S9_L002_1_val_1_bismark_bt2_pe.deduplicated_splitting_report.txt']' returned non-zero exit status 1.
